version: '1.0.{build}'
image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VCPKG_FEATURE_FLAGS: manifests,binarycaching

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat -win64 -disableMetrics
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16 2019"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\TnT.sln

after_build:
  - 7z a TnT-windows-x64.zip %APPVEYOR_BUILD_FOLDER%\build\Release\**.*

cache: c:\tools\vcpkg\installed\

artifacts:
  - path: TnT-windows-x64.zip
    name: x64_build_for_Windows