# TODO: 
# 1. add different builds for x86/x64.
# 2. check for updates weekly.

trigger:
- master

jobs:
  - job: "Generate"
    strategy:
      matrix:
        linux:
          Image: 'ubuntu-latest'
          vpath: "/usr/local/share/vcpkg"
          get_yasm: "sudo apt-get install yasm"
          triplet: x64-linux
          gen: "Unix Makefiles"
        windows:
          Image: 'windows-latest'
          vpath: "C:\\vcpkg"
          get_yasm: "echo" # on Windows, yasm is automatically installed if missing
          triplet: x64-windows
          gen: "Visual Studio 16 2019"
        mac:
          Image: 'macos-latest'
          vpath: "/usr/local/share/vcpkg"
          get_yasm: "brew install yasm"
          triplet: x64-osx
          gen: "XCode"
      maxParallel: 4
    variables:
      VCPKG_DEFAULT_TRIPLET: $(triplet)
      VCPKG_ROOT: $(vpath)
      VCPKG_FEATURE_FLAGS: "manifests,binarycaching"
    
    pool:
      vmImage: $(Image)
    
    steps:
    - task: Cache@2
      inputs:
        key: 'CACHED_DEPS'
        path: '$(vpath)'
        cacheHitVar: 'GOT_CACHE'

    - task: CmdLine@2
      inputs:
        script: |
          $(get_yasm)
      condition: ne(variables.GOT_CACHE, 'true')
    
    - task: CMake@1
      inputs:
        cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -G $(gen)'
    displayName: 'Generate for '

  - job: "Build"
    dependsOn: Generate
    condition: succeeded()
    pool:
      vmImage: $(Image)
    steps:
    - task: CMake@1
      inputs:
        cmakeArgs: '--build .'
      displayName: 'Build for '